---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 785396448573681664-MNBbS6XkXNzFo4sFUuEwgOhZk1isjTC
:access_token_secret: SLLbP9cKc1aOkwhjlAxNXYWDI8Et3vwLVnUerVoW1fnHW
